site_name: Distribution Builder
pages:
    - Home: index.md
    - Quick Start Guide: QuickStart.md
    - High Level Classes: HighLevel.md
    - Low Level Functions: LowLevel.md
    - Configuration Classes: ConfigClasses.md
    - Troubleshooting: Issues.md
    - To-Do List: ToDo.md
    - Contact / Contribute: Contribute.md
theme: readthedocs